### ISSUE TITLE
How to rebuild Plugin

### ISSUE THREAD

**Issue by mateotardini** [Over17/UnityShowAndroidStatusBar#26]
Hi, when a i put "unity-classes.jar" inside "UnityShowAndroidStatusBar-master\src\UnityShowAndroidStatusBar\src\libs" and execute gradlew assemble its keep throwing me error.
Should I put the entire folder inside the unity project or should I run it externally? I only need change statusbar color.

**Comment by Over17** [comment]
Hi! If you want to change the colors only (in resources), then you can unpack the aar (it's just a zip archive), modify it and pack it back. Make sure the result has an extension of `aar`.

Otherwise, it should be possible to build with gradlew if you put the unity library into libs. If you still need it, please share the build log.

**Comment by mateotardini** [comment]
![image](https://user-images.githubusercontent.com/67167909/114894838-5b506880-9de5-11eb-9508-1da2215a9fb1.png)

**Comment by Over17** [comment]
I think the message here is pretty clear - you need to create local.properties and set sdk.dir there (search web for samples) or set ANDROID_HOME env var.
